import type { Product } from "~/lib/db.server";

export const DEMO_PRODUCTS: Product[] = [
  { id: 1, slug: "honey-glaze", name: "Honey Glaze Wave", description: "Body Wave en cheveux humains 100% avec lace HD transparente. Rendu naturel exceptionnel.", price_cad: 485, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 1, stock: 5, image_key: "/images/site/cheveux-ondules-blond.webp", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 2, slug: "midnight-curl", name: "Midnight Deep Curl", description: "Deep Wave intense en noir naturel. Parfaite pour un look glamour et audacieux.", price_cad: 510, compare_at_price_cad: 620, texture: "deep-wave", type_lace: "13x4", longueur_po: 24, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "/images/site/perruque-brune-lisse.webp", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 3, slug: "silk-body", name: "Silk Body Wave", description: "Body Wave soyeux avec closure 5×5 HD. Sans colle pour un port confortable au quotidien.", price_cad: 620, compare_at_price_cad: null, texture: "body-wave", type_lace: "5x5", longueur_po: 26, hd_lace: 1, glueless: 1, pret_a_porter: 0, densite: 180, featured: 0, stock: 4, image_key: "/images/site/presentoirs-boutique.webp", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 4, slug: "polished-straight", name: "Polished Straight", description: "Lisse parfaite prête à porter en moins de 5 minutes. Finition brillante et naturelle.", price_cad: 395, compare_at_price_cad: null, texture: "lisse", type_lace: "glueless", longueur_po: 20, hd_lace: 0, glueless: 1, pret_a_porter: 1, densite: 130, featured: 0, stock: 7, image_key: "/images/site/cheveux-caramel.webp", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 5, slug: "obsidian-curls", name: "Obsidian Curls", description: "Kinky Curly volumineux pour un style afro chic et naturel. Cheveux humains non traités.", price_cad: 440, compare_at_price_cad: null, texture: "kinky-curly", type_lace: "13x4", longueur_po: 18, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 2, image_key: "/images/site/cheveux-ondules-blond.webp", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 6, slug: "caramel-swirl", name: "Caramel Swirl", description: "Body Wave ombré caramel avec lace HD. La touche de couleur parfaite pour l'été.", price_cad: 565, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "/images/site/perruque-brune-lisse.webp", couleur: "ombre", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
];

export const DEMO_MAP = Object.fromEntries(DEMO_PRODUCTS.map(p => [p.slug, p]));
