import type { Product } from "~/lib/db.server";

export const DEMO_PRODUCTS: Product[] = [
  { id: 1, slug: "honey-glaze", name: "Honey Glaze Wave", description: "Body Wave en cheveux humains 100% avec lace HD transparente. Rendu naturel exceptionnel.", price_cad: 485, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 1, stock: 5, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLtATYIhbRck9KGU2ThKBEoqFDUrm0LsQ71wU6frWr5xOoJuCP9RYN3ZNuJXQvnMuDVOIMKX_wPlr3JdHrMuiUz364_oyERzvHH2_4Gy43uVrHIQhoUq_TDDt1nz-HORUexrsLrzxc7knNIgtfxcD2oFeaTfkUBW-YGcRFtbWDYZgf28nMrVisLj9h8ln1sYmeSEnVpoblbhYRZfUiw5eQ_HkpWErPF_J2vEDqPZF54_RRWFYQ4dmbz8kw", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 2, slug: "midnight-curl", name: "Midnight Deep Curl", description: "Deep Wave intense en noir naturel. Parfaite pour un look glamour et audacieux.", price_cad: 510, compare_at_price_cad: 620, texture: "deep-wave", type_lace: "13x4", longueur_po: 24, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLvVcucHmrJHOvNwwz4gKr9Fmqsv6BuvS_dsVPPq3c1WYLx-Iq1r8SvOXSP9BtLdVyJHxMgo85XnvI4n86XAajwiB0pv8bnK3ICHejYoHo1wUSSUqaGXeYk4cRX96XCm-oQ7CEZQy13Dxl-d_JSnCABTG1XGwDYrYPxJAlgrT5BDGBRP8lUD2wkSxbkIxyTs02DkP5gMwXTSg5bitqlkZ5bZ4jb61R4e8taUSVML3Kl4uBtLvxKDWmHm7P0", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 3, slug: "silk-body", name: "Silk Body Wave", description: "Body Wave soyeux avec closure 5×5 HD. Sans colle pour un port confortable au quotidien.", price_cad: 620, compare_at_price_cad: null, texture: "body-wave", type_lace: "5x5", longueur_po: 26, hd_lace: 1, glueless: 1, pret_a_porter: 0, densite: 180, featured: 0, stock: 4, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLs_aaSnXE89RHNSUZEZuCXRK3EyOM8kuJUYogmyeCs5V6fNC1kpVMFwyZ1qUk2woaXd9SOPqETXXvr-zQX_xONFesi_48Wc55zBf_KDar2RY9uo0g3tD-Lb7nqscydgJD6H6XfWBsfbE6Mkvsy0eU6T2N1b4_N7ICoWGEDJ5UzKUsBdcRmgZxjcgxoYWfZ8r7LA4z_zxfm3thiga1P4ZjWin2hj2TWrQ0vGV4pLHzQwx6EhaiEmypx0VtE", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 4, slug: "polished-straight", name: "Polished Straight", description: "Lisse parfaite prête à porter en moins de 5 minutes. Finition brillante et naturelle.", price_cad: 395, compare_at_price_cad: null, texture: "lisse", type_lace: "glueless", longueur_po: 20, hd_lace: 0, glueless: 1, pret_a_porter: 1, densite: 130, featured: 0, stock: 7, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLvBC9t1s695CClir9TlxL0XPPKNaQmzbbn6JTL-kEq_mxKL3WEhzDnLa26givoutSM-wl7pgdn3ZzIi4fuRILNlHUxlmIuTpu-WcVktd7HcQr_mgQH4wM33keoQiY4WK19ap-8-esMLtR9kyNIYDZQormb2F2x1EnqVf06Ik0cDH-6-VW_T39Ibbm1_11DdoykandEDEOVk9Xwv96lCA2wcyKwJY0rIafmIOG9ZQe4EXxEnXUfrYM5Omko", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 5, slug: "obsidian-curls", name: "Obsidian Curls", description: "Kinky Curly volumineux pour un style afro chic et naturel. Cheveux humains non traités.", price_cad: 440, compare_at_price_cad: null, texture: "kinky-curly", type_lace: "13x4", longueur_po: 18, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 2, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLs3oe28jC8kMS-YTVNfj58ZDiv0TCZuor94dCEnJI7fvkdZ3CDmQB1aXjtNDjWH1CnwxDzCC_6Gojto8J62EbQYf1YwwEIoBsDd8mGx-_5NjdONLffhdhrNFKFUj2eAgCMx5NID_6SypvMVJ-b519ieQR8kWeL5WX4R0x4tgeDPBFtL8Q06er8q2espiKzLlgdllR-31OBs3pLQ4GD4TBXhRk90N6ZFvjeBR3W7CNtuOxdwE7tc4mF1_vc", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 6, slug: "caramel-swirl", name: "Caramel Swirl", description: "Body Wave ombré caramel avec lace HD. La touche de couleur parfaite pour l'été.", price_cad: 565, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "https://lh3.googleusercontent.com/aida/AP1WRLt2xTYE9pmbBIvkUMiiUWIs79t8yMhbSgAaHoWUgo6Q3Ax4CrsawVIURgDu1CqcWoeq8gFvJjj-TaJLwfLGj4zBe6xUEshFRpgzMZZ4j1Nv-Y4dk9o_vvoYRfsmlLnjvIeXDpvDcrlUQUbpV_zaz77FffnV-LU6H8nGtjL5VKKTmjairXwA4KauuM9OYz19eI5IB6kr6oncvpmT741osc6CpoMddPSKEpNqcs6QZNnb4mXAK8qgHIRwGMc", couleur: "ombre", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
];

export const DEMO_MAP = Object.fromEntries(DEMO_PRODUCTS.map(p => [p.slug, p]));
