import type { Product } from "~/lib/db.server";

export const DEMO_PRODUCTS: Product[] = [
  { id: 1, slug: "honey-glaze", name: "Honey Glaze Wave", description: "Body Wave en cheveux humains 100% avec lace HD transparente. Rendu naturel exceptionnel.", price_cad: 485, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 1, stock: 5, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuCCbcyZDFlEUORFmblZANwAMfCUCqOkctvG5QFcBrCOQV-nphWsF7tS20ffky6c3CvWhH-MwY9lAhxG4Mx9WFX8sDrVXcRxEy99UbwX4cq2ZfAwB3nqFjDFd76bjPOIfVDVeb8jfNtg7SwYuyT7fGR0ZgYEnAAas-huxvkHdytFje67w2b8064LnqZJ1ymKw6DSATRGodGcXyxaSGqk1BkAxekXOFYgdtoVUSvdEGBMvuN8NHYVJJsLrvxsE9M66QripwgSxnmpoKs", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 2, slug: "midnight-curl", name: "Midnight Deep Curl", description: "Deep Wave intense en noir naturel. Parfaite pour un look glamour et audacieux.", price_cad: 510, compare_at_price_cad: 620, texture: "deep-wave", type_lace: "13x4", longueur_po: 24, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxubQU5RhI8bRCD25p6r_P5QJNuq_tzQhOf2rXOsSUHA0YQPZyw3g75A0k3D_TxdPc912kjItpmb11y438cb2YognsZBqILevEzQvH_2svSgC0rDOIBLqICODzydhQ7urdVYNAQsnr2mAEZkx7FwwyMFXKX6tUyuxN_4KFjAiCCMcH0VtHs8Qv0oJWwz5epfbVUt1-CXOCYxPovgAfAJdy_rZIlcHLEREFsiwKEGn8JbKrX1v16uZ4nklM_xOsPeO3cGn6syU-XaE", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 3, slug: "silk-body", name: "Silk Body Wave", description: "Body Wave soyeux avec closure 5×5 HD. Sans colle pour un port confortable au quotidien.", price_cad: 620, compare_at_price_cad: null, texture: "body-wave", type_lace: "5x5", longueur_po: 26, hd_lace: 1, glueless: 1, pret_a_porter: 0, densite: 180, featured: 0, stock: 4, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuD60WEnVX-_yLSvBntPn9HrU1nMVF-gv9xPTRec1w6rXpr4rqxeI66WP2DFiBaYoulS2wO6R1uIRVXSB1rN_Pj5mbPzb303zLNDW2PMgXnyrLTWDMKLMvhBx22vlId7Jw9fQbhcsxLH7jR3S1tDLkN-zul8kq20lL6nk1BFRFurGFVrK-hXpavqiXVgAlhe7fVFC3PbQwTq9v59NgUOuZ3JIP-wvjMwOaXo_uciqMIP9hB2rhSlCzIgco_KjJbOZGb9ivAfYQEmlXA", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 4, slug: "polished-straight", name: "Polished Straight", description: "Lisse parfaite prête à porter en moins de 5 minutes. Finition brillante et naturelle.", price_cad: 395, compare_at_price_cad: null, texture: "lisse", type_lace: "glueless", longueur_po: 20, hd_lace: 0, glueless: 1, pret_a_porter: 1, densite: 130, featured: 0, stock: 7, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuAY7uaxRnoYo0XebGu4c2gFUG9vOhW_gtOeGGYTeUpOfskjs-B0bR3vtiQf9KBBNjn_ASYUVyTGI2Ao61G6L2jM3vBOaWTymc8op5GMptCg-nRmIbq4-VmbBRwtKPL2g0fuHcjGW7nt9WQ610pDNHrLb0sY4df0OO7x1GESVzyXfwat1I2zRGfcEvWjs6-yVxhH6sfVViLUsBrr1JSOq2vaMtE3wW2RLMhBPIpJMIQJtxdy6TtGM5Xf-VrcJfnq_-K5WcNA4NymnxU", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 5, slug: "obsidian-curls", name: "Obsidian Curls", description: "Kinky Curly volumineux pour un style afro chic et naturel. Cheveux humains non traités.", price_cad: 440, compare_at_price_cad: null, texture: "kinky-curly", type_lace: "13x4", longueur_po: 18, hd_lace: 0, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 2, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuCCbcyZDFlEUORFmblZANwAMfCUCqOkctvG5QFcBrCOQV-nphWsF7tS20ffky6c3CvWhH-MwY9lAhxG4Mx9WFX8sDrVXcRxEy99UbwX4cq2ZfAwB3nqFjDFd76bjPOIfVDVeb8jfNtg7SwYuyT7fGR0ZgYEnAAas-huxvkHdytFje67w2b8064LnqZJ1ymKw6DSATRGodGcXyxaSGqk1BkAxekXOFYgdtoVUSvdEGBMvuN8NHYVJJsLrvxsE9M66QripwgSxnmpoKs", couleur: "naturel", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
  { id: 6, slug: "caramel-swirl", name: "Caramel Swirl", description: "Body Wave ombré caramel avec lace HD. La touche de couleur parfaite pour l'été.", price_cad: 565, compare_at_price_cad: null, texture: "body-wave", type_lace: "13x4", longueur_po: 22, hd_lace: 1, glueless: 0, pret_a_porter: 0, densite: 150, featured: 0, stock: 3, image_key: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxubQU5RhI8bRCD25p6r_P5QJNuq_tzQhOf2rXOsSUHA0YQPZyw3g75A0k3D_TxdPc912kjItpmb11y438cb2YognsZBqILevEzQvH_2svSgC0rDOIBLqICODzydhQ7urdVYNAQsnr2mAEZkx7FwwyMFXKX6tUyuxN_4KFjAiCCMcH0VtHs8Qv0oJWwz5epfbVUt1-CXOCYxPovgAfAJdy_rZIlcHLEREFsiwKEGn8JbKrX1v16uZ4nklM_xOsPeO3cGn6syU-XaE", couleur: "ombre", famille: "perruque", category: "perruque", quantite_meches: null, created_at: "" },
];

export const DEMO_MAP = Object.fromEntries(DEMO_PRODUCTS.map(p => [p.slug, p]));
