name = "ddm-wigs"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[[d1_databases]]
binding = "DB"
database_name = "ddm-wigs-db"
database_id = "0047be0b-294e-471a-b4dd-f94204bb9081"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "ddm-wigs-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "5927b4f2125d40af8892a7edf81f4802"

send_email = [
  { name = "EMAIL", allowed_destination_addresses = ["davesihanou@gmail.com"] }
]

[vars]
ENVIRONMENT = "production"
